### ISSUE TITLE
Exception thrown when connecting to empty DB

### ISSUE THREAD

**Issue by ryanemerson** [gingersnap-project/debezium_poc#21]
This only occurs if you forget to execute `populate.sql` before `quarkus dev`.

```
2022-11-02 12:45:15,414 INFO  [io.deb.con.mys.MySqlStreamingChangeEventSource] (debezium-mysqlconnector-us-east-change-event-source-coordinator) Waiting for keepalive thread to start
2022-11-02 12:45:15,414 INFO  [io.deb.uti.Threads] (blc-localhost:3306) Creating thread debezium-mysqlconnector-us-east-binlog-client
2022-11-02 12:45:15,415 ERROR [io.deb.con.mys.MySqlStreamingChangeEventSource] (blc-localhost:3306) Error during binlog processing. Last offset stored = null, binlog reader near position = binlog.000002/2772
2022-11-02 12:45:15,415 INFO  [com.git.shy.mys.bin.BinaryLogClient] (blc-keepalive-localhost:3306) threadExecutor is shut down, terminating keepalive thread
2022-11-02 12:45:15,416 ERROR [io.deb.pip.ErrorHandler] (blc-localhost:3306) Producer failure: io.debezium.DebeziumException: Client requested master to start replication from position > file size Error code: 1236; SQLSTATE: HY000.
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1229)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1274)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1079)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: Client requested master to start replication from position > file size
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1043)
	... 3 more

```

**Comment by wburns** [comment]
This definitely never happened before as originally we didn't even have the populate.sql file. Let me see if I can reproduce.

**Comment by wburns** [comment]
@ryanemerson Can you provide the entire CLI output? I am unable to reproduce, the only thing that should be different is I have some schema updates, but you should have that already with the setup.sql script running.
